config/routes.rb
 Rails.application.routes.draw do

resources :blogs

root 'webpages#home'

get 'about', to:'webpages#about'

get 'signup', to:'users#new'

resources :users, except: [:new]

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	validates :apellation, presence:true, 
	           length: {minimum:4, maximum: 50}
    validates :caption, presence:true, 
               length: {minimum:10, maximum: 100}
	validates :specification, presence:true, 
	           length: {minimum:4, maximum: 50}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	    before_save { self.email =  email.downcase }
	    has_many :blogs
	    validates :username, presence: true, 
	              uniqueness: { case_sensitive:  false},
	              length: {minimum: 2, maximum: 32}
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
        validates :email, format: {with: VALID_EMAIL_REGEX},
                  uniqueness: { case_sensitive:  false},
	              length: {maximum: 100}
	    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	 before_action :find_blog, only: [:edit, :show, :destroy, :update]
     def index
     	@b = Blog.all
     end
	 def new
		@b = Blog.new
	 end
	 def edit
	 end
     def show
     end
     def destroy
     	@b.destroy
     	flash[:danger] = "Blog was deleted"
     	redirect_to blogs_path
     end
	 def create
	     @b = Blog.new(blog_params)
          @b.user = User.find(3)
	     @b.save
	     if @b.save
	     	flash[:success] = 'Blog is successfully created'
	     	redirect_to blog_path(@b)
	     else
	     	render 'new'
	     end
	 end
     def update
     	if @b.update(blog_params)
     		flash[:success] = "Blog is successfully updated"
     		redirect_to blog_path(@b)
     	else 
     		render 'edit'
     	end
     end
     private
     def blog_params
     	params.require(:blog).permit(:apellation, :caption, :specification)
     end
     def find_blog
     	@b = Blog.find(params[:id])
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new 
		@u = User.new
	end
    def create 
    	@u = User.new(user_params)
        if @u.save
	    	flash[:success] = "Welcome to Alpha Blog #{@u.username}"
	        redirect_to blogs_path
	    else 
	    	render 'new'
	    end
	end
	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
def  home
#puts 'this is home function'
end
def about
#puts 'this  is about function'
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_form.html.erb
<%= render 'shared/errors', obj:@b %>


<div class="col-sm-12">
	<%= form_for(@b, :html => {class: "form-horizontal", role:"form" }) do |f| %>
        <div class="form-group">
	        <div class="col-sm-2 control-label">
				<%= f.label :apellation, class: "form-head" %> 
			</div>
			<div class="col-sm-10">
				<%= f.text_field :apellation, class: "form-control",placeholder: "Type your apellation here",autofocus: "true" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :caption, class: "form-head" %>
			</div>
			<div class="col-sm-10">
				<%= f.text_area :caption , class: "form-control", placeholder: "Type your caption here"  %>
			</div>
        </div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :specification, class: "form-head" %>
			</div>
			<div class="col-sm-10">
				<%= f.text_area :specification, class: "form-control",placeholder: "Type your specification here"  %> 
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: "btn btn-primary create-btn" %>
				<%= link_to 'Back', blogs_path, class: "col-sm-offset-11 back" %>
			</div>
		</div>	 
	<% end %>
</div>

app/views/blogs/edit.html.erb
<h1 class="new-h1"> UPDATE YOUR BLOG </h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 align="center"> <b>Daily Blogs </b></h1>
<%= link_to 'Create new blog', new_blog_path, class: "index-create-new-blog" %>
<% @b.each do |bl| %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="well well-lg well-index">
        <div  class="b-apellation">
          <%= link_to bl.apellation, blog_path(bl) %>
        </div>
        <div class="b-caption">
           <%= link_to truncate(bl.caption, length: 20), blog_path(bl) %>
        </div>
        <div class="b-specification">
           <%= link_to truncate(bl.specification, length: 20), blog_path(bl) %>
        </div>
        <small class="blog-meta-details"> 
          Created by: <%= bl.user.username if bl.user %>
          <%= time_ago_in_words(bl.created_at) %> ago, 
          last updated: <%= time_ago_in_words(bl.updated_at) %> 
        </small>
        <div class="index-button">
           <%= link_to 'Edit', edit_blog_path(bl), class: "btn btn-primary btn-sm" %>
           <%= link_to 'Delete', blogs_path, method: :delete, 
                  data:{ cofirm: "Are u sure u want to delete this blog?" }, class: "btn btn-danger btn-sm" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/new.html.erb
<h1 class="new-h1"> CREATE YOUR OWN BLOG</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb

	<h1 align="center">Apellation: <%= @b.apellation %></h1>
	<div class="well col-sm-10 col-sm-offset-1">
		<h3 align="center" >Caption:</h3>
		<%= @b.caption %>
	    </br>
		<h3 align="center">
			<strong>Specificaion:</strong>
			</br>
			<%= @b.specification %>
		</h3>
		<%= link_to 'Edit', edit_blog_path, class: "btn btn-primary" %>
		<%= link_to 'Delete', blog_path, method: :delete, 
		            data:{cofirm:"Are u sure u want to delete ur blog?"}, 
		            class: "btn btn-danger" %>
		<%= link_to 'View all blogs', blogs_path , class: "btn btn-info" %>
	</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="footer">
	Copyright &copy By <a href="https://www.google.com" class="enterprises"> Rajat Enterprises Limited </a> <%= link_to 'About', about_path, class: "about" %> 
	</div>
</div>

app/views/layouts/_messages.html.erb

    <div class="col-xs-10 col-xs-offset-1">
	    <% flash.each do|name, msg| %>
		    <div class='alert alert-<%= "#{name}" %> alert-dissimible' role="alert"> 
			    <button type="button" class="close" data-dismiss="alert" >&times;</button>
				 <ul>
					 <li><%= content_tag :div, msg,:id=> "flash_#{name}" if msg.is_a?(String) %></li>
				</ul>
			</div>
		<% end %>
	</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="progress">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
        <span class="sr-only">45% Complete</span>
      </div>
    </div>


    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", blogs_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New", new_blog_path %></li>
            <li><%= link_to "Index", blogs_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="col-sm-8 col-sm-offset-2">
	    <div class="alert alert-danger alert-dissimible" role="alert">
		    <button type="button" class="close error-x" data-dismiss="alert" >&times;</button>
		         <h2 class="error-h2"> Your Blog has following <%= pluralize(obj.errors.count,"Error")  %> </h2>
				 <ul>
					 <% obj.errors.full_messages.each do |msg| %>
						 <li> <%= msg %> </li>
					 <% end %>
				 </ul>
		 </div>
	 </div>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj:@u %>


<div class="col-sm-12">
	<%= form_for(@u, :html => {class: "form-horizontal", role:"form" }) do |f| %>
        <div class="form-group">
	        <div class="col-sm-2 control-label">
				<%= f.label :username, class: "form-head" %> 
			</div>
			<div class="col-sm-10">
				<%= f.text_field :username, class: "form-control",placeholder: "Enter your name",autofocus: "true" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :email, class: "form-head" %>
			</div>
			<div class="col-sm-10">
				<%= f.email_field :email , class: "form-control", placeholder: "Enter your email"  %>
			</div>
        </div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :password, class: "form-head" %>
			</div>
			<div class="col-sm-10">
				<%= f.password_field :password, class: "form-control",placeholder: "Enter password"  %> 
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit "SignUp", class: "btn btn-primary create-btn" %>
				<%= link_to 'Back', blogs_path, class: "col-sm-offset-11 back" %>
			</div>
		</div>	 
	<% end %>
</div>

app/views/webpages/about.html.erb
Hi there u r in about template
<%= link_to 'Home', root_path %>

app/views/webpages/home.html.erb

	<div class="jumbotron" align="center"> 
		<h1> ALPHA BLOG</h1> 	
		<%= link_to "Sign Up for Free", "#" , class:"btn btn-primary btn-lg" %>
	</div>
	